name: rlpro
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - fastapi
  - uvicorn
  - pydantic
  - pydantic-settings
  - httpx
  - numpy
  - pandas
  - rich
  - pytest
  - pip:
      - openvino
      - openvino-tokenizers
      - tiktoken
      - pymupdf
